language: node_js
node_js:
  - "0.10"
install:
  - npm install
  - npm install -g bower grunt-cli
  - bower cache clean
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 'grunt karma:firefox'